include $(TOPDIR)/rules.mk
PKG_NAME:=luci-app-sovereign
PKG_RELEASE:=6
PKG_VERSION:=0.2.2
LUCI_TITLE:=Sovereign OS
LUCI_DEPENDS:=+luci +rpcd +ubus
LUCI_PKGARCH:=all
include $(TOPDIR)/feeds/luci/luci.mk
