name: Package Sovereign Overlay (GL-BE3600 stock firmware)
on: { workflow_dispatch: {} }

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create rootfs overlay
        run: |
          set -e
          mkdir -p overlay
          [ -d files/etc ] && rsync -a files/etc/ overlay/etc/
          [ -d files/www ] && rsync -a files/www/ overlay/www/
          if [ -d package/sovereign-core/files ]; then
            rsync -a package/sovereign-core/files/etc/ overlay/etc/ 2>/dev/null || true
            rsync -a package/sovereign-core/files/usr/ overlay/usr/ 2>/dev/null || true
          fi
          if [ -d package/luci-app-sovereign/root ]; then
            rsync -a package/luci-app-sovereign/root/ overlay/
          fi
          # Make init/defaults executable if present
          find overlay/etc/init.d -type f -print0 2>/dev/null | xargs -0 chmod +x || true
          find overlay/etc/uci-defaults -type f -print0 2>/dev/null | xargs -0 chmod +x || true
          find overlay/usr/sbin -type f -print0 2>/dev/null | xargs -0 chmod +x || true
          tar -C overlay -czf sovereign-overlay.tar.gz .

      - name: Bundle installer + overlay + checksums
        run: |
          mkdir out
          cp scripts/install.sh out/
          cp sovereign-overlay.tar.gz out/
          (cd out && shasum -a 256 * > SHA256SUMS.txt)

      - name: Upload overlay installer
        uses: actions/upload-artifact@v4
        with:
          name: sovereign-os-be3600-overlay
          path: out/*
