name: Build Sovereign OS (GL-BE3600)
on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3 rsync unzip zlib1g-dev file wget jq

      - name: Clone OpenWrt 23.05.3
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git checkout v23.05.3

      - name: Inject Sovereign OS tree
        run: |
          rsync -a --exclude '.github' ./ openwrt/

      - name: Use pinned feeds + cache downloads
        run: |
          cd openwrt
          cp ./feeds.conf ./feeds.conf.bak 2>/dev/null || true
          mv ../feeds.conf ./feeds.conf
      - name: Cache OpenWrt downloads
        uses: actions/cache@v3
        with:
          path: openwrt/dl
          key: dl-${{ runner.os }}-${{ hashFiles('feeds.conf') }}
          restore-keys: |
            dl-${{ runner.os }}-

      - name: Update feeds (pinned) and install only needed packages
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install \
            luci luci-ssl luci-compat luci-lib-jsonc \
            uhttpd rpcd uci \
            iwinfo iw curl coreutils jq avahi-daemon alsa-utils htop iperf3 usbutils \
            ca-bundle ca-certificates

      - name: Defconfig
        run: |
          cd openwrt
          cp ./files/sovereign_config_examples/.config .config
          make defconfig

      - name: Build firmware
        run: |
          cd openwrt
          make download -j8
          make -j"$(nproc)" V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sovereign-os-be3600-firmware
          path: |
            openwrt/bin/targets/*/*/openwrt-*.bin
            openwrt/bin/packages/**
