name: Build Sovereign OS (GL-BE3600)
on: { workflow_dispatch: {} }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3 rsync unzip zlib1g-dev file wget jq
      - name: Clone OpenWrt
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git checkout v23.05.3
      - name: Inject Sovereign OS
        run: |
          rsync -a --exclude '.github' ./ openwrt/
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp ./files/sovereign_config_examples/.config .config
          make defconfig
      - name: Build firmware
        run: |
          cd openwrt
          make -j$(nproc) V=s
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sovereign-os-be3600-firmware
          path: |
            openwrt/bin/targets/*/*/openwrt-*.bin
            openwrt/bin/packages/**
